# Charseq

In [56]:
import torch
import numpy as np

In [57]:
'''
    HIHELLO Example by PyTorch
'''

'\n    HIHELLO Example by PyTorch\n'

In [58]:
# whole unique character used in word
char_set = ['h', 'i', 'e', 'l', 'o']

# hyper parameters
input_size = len(char_set)
hidden_size = len(char_set)
learning_rate = 0.01

# data setting
x_data = [[0, 1, 0, 2, 3, 3]] # means 'hihell'
x_one_hot = [[[1, 0, 0, 0, 0],# means 'h'
             [0, 1, 0, 0, 0], # means 'i'
             [1, 0, 0, 0, 0],
             [0, 0, 1, 0, 0],
             [0, 0, 0, 1, 0],
             [0, 0, 0, 1, 0]]]

y_data = [[1, 0, 2, 3, 3, 4]] # means 'ihello'

In [59]:
# to tensor
X = torch.FloatTensor(x_one_hot)
Y = torch.LongTensor(y_data)

print(X)
print(Y)

tensor([[[1., 0., 0., 0., 0.],
         [0., 1., 0., 0., 0.],
         [1., 0., 0., 0., 0.],
         [0., 0., 1., 0., 0.],
         [0., 0., 0., 1., 0.],
         [0., 0., 0., 1., 0.]]])
tensor([[1, 0, 2, 3, 3, 4]])


In [60]:
'''
    More general way to set Charseq
'''

'\n    More general way to set Charseq\n'

In [61]:
sample = 'if you want you'

# make dict
char_set = list(set(sample)) # pick unique characters
char_dic = {c: i for i, c in enumerate(char_set)}
print(char_dic)

# hyper parameters
dic_size = len(char_dic) # length of whole characters used in sentence
hidden_size = len(char_dic)
learning_rate = 0.1

# data setting
sample_idx = [char_dic[c] for c in sample] # char to idx
x_data = [sample_idx[:-1]] # except for last character
print(x_data)

x_one_hot = [np.eye(dic_size)[x] for x in x_data] # idx to one hot encoding by np.eye()
print(x_one_hot)

y_data = [sample_idx[1:]] # except for first character

# final X, Y
X = torch.FloatTensor(x_one_hot)
Y = torch.LongTensor(y_data)

{'i': 0, 'f': 1, 'a': 2, 'o': 3, 'n': 4, 'y': 5, 'w': 6, 't': 7, 'u': 8, ' ': 9}
[[0, 1, 9, 5, 3, 8, 9, 6, 2, 4, 7, 9, 5, 3]]
[array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.]])]


In [62]:
print(X)
print(Y)

tensor([[[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
         [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
         [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
         [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
         [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
         [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
         [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.]]])
tensor([[1, 9, 5, 3, 8, 9, 6, 2, 4, 7, 9, 5, 3, 8]])


In [63]:
# RNN
rnn = torch.nn.RNN(dic_size, hidden_size, batch_first=True) # batch_first => put batch_size on the first place => (B, S, F)

In [64]:
# cost and optimizer
criterion = torch.nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(rnn.parameters(), lr=learning_rate)

In [70]:
# train
for i in range(100):
    outputs, _status = rnn(X)
    loss = criterion(outputs.view(-1, dic_size), Y.view(-1))
    
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    
    print('outputs data: ', outputs.data.numpy())
    result = outputs.data.numpy().argmax(axis=2)
    print('result squeeze: ', np.squeeze(result))
    result_str = ''.join([char_set[c] for c in np.squeeze(result)])
    print(i, "loss: ", loss.item(), "prediction: ", result, "true Y: ", y_data, "prediction str: ", result_str)

outputs data:  [[[-0.9989896   0.9993565  -0.9987239  -0.99914384 -0.9981229
   -0.9989207  -0.9977825  -0.99704397 -0.99863684 -0.99753475]
  [-0.9999847  -0.99990493 -0.9998418  -0.99880683 -0.99951696
   -0.99981034 -1.         -0.99986404 -0.9992038   0.9998096 ]
  [-0.9999998  -0.99999934 -0.99997073 -0.99965787 -0.9997313
    0.9997728  -0.93907464 -0.99981654 -0.9999629  -0.9995406 ]
  [-0.99999994 -0.99999994 -0.9990808   0.99949497 -0.9999926
   -0.99993163 -1.         -0.99948955 -0.9997897  -0.9994492 ]
  [-0.9999926  -0.99999756 -0.9998953  -0.999506   -0.9993865
   -0.9999349  -1.         -0.99958235  0.9998599  -0.9999302 ]
  [-0.99999994 -0.9999999  -0.9994176  -0.9997014  -0.712945
   -0.99961704 -1.         -0.48298937 -0.9999989   0.9999261 ]
  [-0.9999979  -0.99999183 -0.99998343 -0.9997661  -0.9996495
    0.9997437   0.98752344 -0.99981445 -0.9999733  -0.9990106 ]
  [-0.99999857 -0.99999624  0.9996655  -0.99432266 -0.99947673
   -0.9999982  -1.         -0.99976367 -

outputs data:  [[[-0.999131    0.99945295 -0.9988731  -0.99923664 -0.998332
   -0.9990599  -0.99803084 -0.9974937  -0.99881434 -0.997899  ]
  [-0.99998677 -0.9999089  -0.999868   -0.99902153 -0.99958134
   -0.99982244 -1.         -0.9998761  -0.9993219   0.99983853]
  [-0.9999998  -0.99999934 -0.9999751  -0.9997123  -0.99976516
    0.9998045  -0.94316965 -0.999833   -0.99996614 -0.99960095]
  [-0.99999994 -0.99999994 -0.99918306  0.999578   -0.9999934
   -0.99993575 -1.         -0.9995727  -0.9998128  -0.9995342 ]
  [-0.9999934  -0.99999756 -0.9999125  -0.9995929  -0.9994888
   -0.99993837 -1.         -0.9996514   0.9998799  -0.99993014]
  [-0.99999994 -0.9999999  -0.9995382  -0.9997377  -0.73232615
   -0.9996504  -1.         -0.49958682 -0.999999    0.99993396]
  [-0.99999833 -0.99999297 -0.99998564 -0.9997993  -0.9997041
    0.9997763   0.98843133 -0.9998374  -0.99997556 -0.99911636]
  [-0.99999875 -0.9999961   0.9997102  -0.995273   -0.99953556
   -0.9999983  -1.         -0.9998051 

outputs data:  [[[-0.9992227   0.99951416 -0.99897367 -0.9992996  -0.9984751
   -0.99915206 -0.99820083 -0.99777853 -0.99893165 -0.9981315 ]
  [-0.9999881  -0.99991196 -0.99988425 -0.999152   -0.9996237
   -0.9998314  -1.         -0.9998844  -0.99939775  0.99985677]
  [-0.9999998  -0.99999934 -0.9999778  -0.9997464  -0.9997876
    0.9998246  -0.945935   -0.99984443 -0.9999684  -0.99964154]
  [-0.99999994 -0.99999994 -0.9992525   0.99962944 -0.99999386
   -0.9999388  -1.         -0.99962443 -0.9998285  -0.999588  ]
  [-0.9999939  -0.9999975  -0.9999233  -0.9996459  -0.9995526
   -0.999941   -1.         -0.99969417  0.9998927  -0.99993026]
  [-0.99999994 -0.9999999  -0.9996094  -0.9997616  -0.74660164
   -0.9996743  -1.         -0.5107078  -0.99999905  0.9999393 ]
  [-0.99999857 -0.9999937  -0.99998707 -0.99982077 -0.99973905
    0.99979746  0.98904085 -0.9998537  -0.9999772  -0.99918747]
  [-0.9999988  -0.999996    0.9997392  -0.9958585  -0.99957573
   -0.99999833 -1.         -0.9998304