In [8]:
import numpy as np

# L1 norm
def l1_norm(x):
    a = np.abs(x)
    a = np.sum(a)
    return a

# L2 norm
def l2_norm(x):
    a = x * x
    a = np.sum(a)
    a = np.sqrt(a)
    return a

# 벡터 생성 및 norm 확인
b = np.array([1, 2, 3, 4, 5])
print(l1_norm(b))
print(l2_norm(b))

15
7.416198487095663


In [11]:
# 벡터의 내적
def get_angle(x, y):
    angle = np.inner(x, y) / l2_norm(x) * l2_norm(y)
    # cos => 각도 구하기
    angle = np.arccos(angle)
    return angle

x = np.array([1, 2, 3, 4, 5])
y = np.array([10, 22, 32, 44, 52])
print(get_angle(x, y))

nan


C:\anaconda3\envs\gpuenv\lib\site-packages\ipykernel_launcher.py:4: RuntimeWarning: invalid value encountered in arccos
  after removing the cwd from sys.path.


In [12]:
# 행렬 => numpy 에서는 기본적으로 행벡터가 기준
a = np.arange(9).reshape(3, 3)

# 행벡터 x 열벡터 => 내적
print(np.dot(a, a))

# 행벡터 x 행벡터
print(np.inner(a, a))

[[ 15  18  21]
 [ 42  54  66]
 [ 69  90 111]]
[[  5  14  23]
 [ 14  50  86]
 [ 23  86 149]]


In [19]:
# 역행렬
# np.linalg.inv(a)