In [ ]:
import numpy as np

In [22]:
# 문자열 => 자동으로 dtype 에 맞춰 변경
arr = np.array([1, 2, 3, 4, "5", "6"], dtype=np.float32)
print(arr)
print(arr.shape)

# 차원수
print(arr.ndim)
# 데이터 갯수
print(arr.size)
# 사이즈는 동일하나 형태 변경 => 2 x 3 행렬
# reshape(-1, 4) => -1 = 컬럼 사이즈 유지하면서 알아서 row 사이즈 반영해 줌
print(arr.reshape(2, 3))

[1. 2. 3. 4. 5. 6.]
(6,)
1
6
[[1. 2. 3.]
 [4. 5. 6.]]


In [24]:
np.arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [26]:
# 시작 / 끝 / 스텝
# 메소드 체이닝 적용 가능
np.arange(1, 100, 10).reshape(2, 5)

array([[ 1, 11, 21, 31, 41],
       [51, 61, 71, 81, 91]])

In [28]:
# 기본 실수형
np.zeros((2, 10), dtype=np.int8)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int8)

In [30]:
# 대각 성분 추출
matrix = np.arange(9).reshape(3, 3)
# k => 시작 인덱스
np.diag(matrix, k=2)

array([2])

In [33]:
# 모든 row 합
print(matrix.sum(axis=0))
# 모든 col 합
print(matrix.sum(axis=1))

[ 9 12 15]
[ 3 12 21]


In [40]:
# concat => vstack / hstack
matrix_a = np.arange(10).reshape(2, 5)
matrix_b = np.arange(10).reshape(2, 5)

# 수직 기준 합치기
np.vstack((matrix_a, matrix_b))
# 수평 기준 합치기
np.hstack((matrix_a, matrix_b))

array([[0, 1, 2, 3, 4, 0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9, 5, 6, 7, 8, 9]])

In [41]:
# 내적 곱 (중요)
matrix_a = np.arange(10).reshape(2, 5)
matrix_b = np.arange(10).reshape(5, 2)

# shape => 2 x 2
np.dot(matrix_a, matrix_b)

array([[ 60,  70],
       [160, 195]])

In [43]:
# 브로드캐스팅 => 주로 matrix or vector + scala 연산 시 사용
matrix_a + 100
matrix_a + [1, 2, 3, 4, 5]

array([[ 1,  3,  5,  7,  9],
       [ 6,  8, 10, 12, 14]])

In [45]:
# any / all
np.all(matrix_a < 100)
np.any(matrix_a < 100)

True

In [53]:
# where => 조건에 해당하는 인덱스 리턴
np.where(matrix_a < 5)

(array([0, 0, 0, 0, 0], dtype=int64), array([0, 1, 2, 3, 4], dtype=int64))

In [58]:
# argmax / argmin (중요) => 최대값 및 최소값에 해당하는 인덱스 리턴

# 각 row 들의 같은 인덱스의 값 비교
print(np.argmax(matrix_a, axis=0))
# 각 col 들의 같은 인덱스의 값 비교
print(np.argmin(matrix_a, axis=1))

[1 1 1 1 1]
[0 0]
