In [45]:
'''
    Logistic Regression by PyTorch
'''

'\n    Logistic Regression by PyTorch\n'

In [46]:
import torch

'''
    Binary Classification
'''

# create raw data
x_train = [[1, 2], [2, 3], [3, 1], [4, 3], [5, 3], [6, 2]]
y_train = [[0], [0], [0], [1], [1], [1]]

In [47]:
# create tensor
x_train = torch.FloatTensor(x_train)
y_train = torch.FloatTensor(y_train)

In [48]:
# check input and output (label)
print(x_train)
print(y_train)

tensor([[1., 2.],
        [2., 3.],
        [3., 1.],
        [4., 3.],
        [5., 3.],
        [6., 2.]])
tensor([[0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.]])


In [49]:
# set weights and bias
W = torch.zeros((2, 1), requires_grad=True)
b = torch.zeros(1, requires_grad=True)

In [50]:
# set hypothesis => sigmoid function
hypothesis = 1 / (1 + torch.exp(-(x_train.matmul(W) + b)))
print(hypothesis)
print(hypothesis.size())
print(hypothesis.shape)

# sigmoid by torch
# torch.sigmoid(x_train.matmul(W) + b)

tensor([[0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000]], grad_fn=<MulBackward0>)
torch.Size([6, 1])
torch.Size([6, 1])


In [51]:
# calc cost => 1st cost result example
cost = -(y_train[0] * torch.log(hypothesis[0]) + (1 - y_train) * torch.log(1 - hypothesis[0]))
cost

tensor([[0.6931],
        [0.6931],
        [0.6931],
        [0.0000],
        [0.0000],
        [0.0000]], grad_fn=<NegBackward>)

In [52]:
# mean of whole cost
print(cost.mean())

tensor(0.3466, grad_fn=<MeanBackward1>)


In [53]:
# briefly
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

torch.manual_seed(1)

F.binary_cross_entropy(hypothesis, y_train)

tensor(0.6931, grad_fn=<BinaryCrossEntropyBackward>)

In [54]:
# training procedure
torch.manual_seed(1)

# GD
optimizer = optim.SGD([W, b], lr=1)

epoch_nb = 1000
for epoch in range(1 + epoch_nb):
    hypothesis = torch.sigmoid(x_train.matmul(W) + b)
    cost = F.binary_cross_entropy(hypothesis, y_train)
    
    optimizer.zero_grad() # to avoid accumulate gradient value
    cost.backward()       # back propagation with new gradient value
    optimizer.step()      # update weights and bias
     
    if epoch % 100 == 0:
        print(f'Epoch: {epoch:4d}/{epoch_nb}, cost: {cost.item():.5f}')

Epoch:    0/1000, cost: 0.69315
Epoch:  100/1000, cost: 0.13472
Epoch:  200/1000, cost: 0.08064
Epoch:  300/1000, cost: 0.05790
Epoch:  400/1000, cost: 0.04530
Epoch:  500/1000, cost: 0.03726
Epoch:  600/1000, cost: 0.03167
Epoch:  700/1000, cost: 0.02756
Epoch:  800/1000, cost: 0.02439
Epoch:  900/1000, cost: 0.02189
Epoch: 1000/1000, cost: 0.01985


In [57]:
# evaluation by test dataset

print(W)
print(b)

x_test = torch.FloatTensor([[2, 5], [7, 10]])
final_hyptothesis = torch.sigmoid(x_test.matmul(W) + b)

# check probability each input values
print(final_hyptothesis[:])

tensor([[3.2530],
        [1.5179]], requires_grad=True)
tensor([-14.4819], requires_grad=True)
tensor([[0.4046],
        [1.0000]], grad_fn=<SliceBackward>)


In [64]:
# inheritance
class BinaryClassifier(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(2, 1) # linear => wx + b / (2, 1) => size of weights / bias = 1
        self.sigmoid = nn.Sigmoid()
        
    # model(x_train) => automatically call this function for forward propagation
    def forward(self, x):
        return self.sigmoid(self.linear(x))
    
    
model = BinaryClassifier()

In [65]:
# renew training procedure
torch.manual_seed(1)

# model.parameters() => [W, b]
optimizer = optim.SGD(model.parameters(), lr=1)

epoch_nb = 1000
for epoch in range(1 + epoch_nb):
    
    # model => BinaryClassifier
    hypothesis = model(x_train)
    cost = F.binary_cross_entropy(hypothesis, y_train)
    
    optimizer.zero_grad() # to avoid accumulate gradient value
    cost.backward()       # back propagation with new gradient value
    optimizer.step()      # update weights and bias
     
    if epoch % 100 == 0:
        print(f'Epoch: {epoch:4d}/{epoch_nb}, cost: {cost.item():.5f}')

Epoch:    0/1000, cost: 0.53971
Epoch:  100/1000, cost: 0.13427
Epoch:  200/1000, cost: 0.08049
Epoch:  300/1000, cost: 0.05782
Epoch:  400/1000, cost: 0.04525
Epoch:  500/1000, cost: 0.03723
Epoch:  600/1000, cost: 0.03165
Epoch:  700/1000, cost: 0.02754
Epoch:  800/1000, cost: 0.02438
Epoch:  900/1000, cost: 0.02188
Epoch: 1000/1000, cost: 0.01984
