In [4]:
'''
    PyTorch: seems like Numpy
'''
import torch
t = torch.FloatTensor([1, 2, 3, 4, 5])
t

tensor([1., 2., 3., 4., 5.])

In [11]:
print(t.size())
print(t.dim())
print(t[:])

torch.Size([5])
1
tensor([1., 2., 3., 4., 5.])


In [17]:
t1 = torch.FloatTensor([1, 2, 3, 4, 5])
t2 = torch.FloatTensor([2, 3, 4, 5, 6])
t3 = torch.FloatTensor([3])

In [18]:
print(t1 + t2)
print(t1 * t2)

# automatically add t3 as Scala
print(t1 + t2 + t3)

tensor([ 3.,  5.,  7.,  9., 11.])
tensor([ 2.,  6., 12., 20., 30.])
tensor([ 6.,  8., 10., 12., 14.])


In [19]:
# automatically dot t2 as v-col => (1, 5) x (5, 1) = (1, 1)
print(t1.matmul(t2))

tensor(70.)


In [21]:
# element-wise multiplication
print(t1.mul(t2))

tensor([ 2.,  6., 12., 20., 30.])


In [26]:
# aggregate functions
print(t1.mean())
print(t1.std())
print(t1.var())
print(t1.sum())

tensor(3.)
tensor(1.5811)
tensor(2.5000)
tensor(15.)


In [32]:
t4 = torch.FloatTensor([[1, 2], [3, -4]])
t4

tensor([[ 1.,  2.],
        [ 3., -4.]])

In [33]:
# dim = axis

# dim=0 => col
# dim=1 => row
print(t4.sum(dim=0))
print(t4.sum(dim=1))
print(t4.sum(dim=-1))

tensor([ 4., -2.])
tensor([ 3., -1.])
tensor([ 3., -1.])


In [38]:
# max => value + index
print(t4.max(dim=0))
print(t4.max(dim=1))

# argmax => only index
print(t4.argmax(dim=0))
print(t4.argmax(dim=1))

(tensor([3., 2.]), tensor([1, 0]))
(tensor([2., 3.]), tensor([1, 0]))
tensor([1, 0])
tensor([1, 0])


In [ ]:
print('===============================================')

In [46]:
# view = reshape / -1 means N
print(t4.view(-1).shape)
print(t4.view(-1).dim())

# (1, 4)
print(t4.view(-1, 4).shape)
print(t4.view(-1, 4).dim())

# (4, 1)
print(t4.view(4, -1))
print(t4.view(4, -1).dim())

torch.Size([4])
1
torch.Size([1, 4])
2
tensor([[ 1.],
        [ 2.],
        [ 3.],
        [-4.]])
2


In [49]:
# squeeze => delete 1-dim
print(t4.view(4, -1).shape)
print(t4.view(4, -1).squeeze().shape)

torch.Size([4, 1])
torch.Size([4])


In [55]:
t5 = t4.view(4, -1).squeeze()

# recreate 1-dim
print(t5.unsqueeze(1).shape)

torch.Size([4, 1])


In [57]:
# casting
lt = torch.LongTensor([1, 2, 3, 4, 5])
lt

tensor([1, 2, 3, 4, 5])

In [58]:
bt = torch.ByteTensor([1, 2, 3, 4, 5])
bt

tensor([1, 2, 3, 4, 5], dtype=torch.uint8)

In [62]:
# concat
print(torch.cat([t1, t2], dim=0))

tensor([1., 2., 3., 4., 5., 2., 3., 4., 5., 6.])


In [64]:
# stacking => automatically change dimension
print(torch.stack([t1, t2], dim=0))
print(torch.stack([t1, t2], dim=1))

tensor([[1., 2., 3., 4., 5.],
        [2., 3., 4., 5., 6.]])
tensor([[1., 2.],
        [2., 3.],
        [3., 4.],
        [4., 5.],
        [5., 6.]])


In [66]:
# ones / zeros => change all elements into 0 or 1
x = torch.FloatTensor([[1, 2, 3], [1, 2, 3]])
print(torch.ones_like(x))
print(torch.zeros_like(x))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [68]:
# inplace by underscore (_)
print(t1.mul_(t2))
print(t1)

tensor([ 2.,  6., 12., 20., 30.])
tensor([ 2.,  6., 12., 20., 30.])
